### ISSUE TITLE
Support `<picture>` block

### ISSUE THREAD

**Issue by LitoMore** [mondeja/strip-gh-theme-links#22]
Contributes to https://github.com/simple-icons/simple-icons/pull/7950

### Example

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://si-cdn.vercel.app/simpleicons/white">
  <source media="(prefers-color-scheme: light)" srcset="https://si-cdn.vercel.app/simpleicons">
  <img alt="Simple Icons" width=70 src="https://si-cdn.vercel.app/simpleicons">
</picture>
```

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://si-cdn.vercel.app/simpleicons/white">
  <source media="(prefers-color-scheme: light)" srcset="https://si-cdn.vercel.app/simpleicons">
  <img alt="Simple Icons" width=70 src="https://si-cdn.vercel.app/simpleicons">
</picture>

### References

- [**Specifying the theme an image is shown to**](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)

**Comment by mondeja** [comment]
In fact, the current method of the library is deprecated:

> The old method of specifying images based on the theme, by using a fragment appended to the URL (`#gh-dark-mode-only` or `#gh-light-mode-only`), is deprecated and will be removed in favor of the new method described above.
