### ISSUE TITLE
Add tests for more cases

### ISSUE THREAD

**Issue by LitoMore** [mondeja/strip-gh-theme-links#25]
https://github.com/mondeja/strip-gh-theme-links/blob/fb82e5fb03542a23e008b1722b4dca3c97934aee/tests/unit/package.ts#L5-L15

We also need to test these cases below:

```html
<!-- dark only -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/dark">
  <img alt="Alt text" title="Title text" src="https://user-images.githubusercontent.com/default" width=70>
</picture>
```

```html
<!-- light only -->
<picture>
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/light">
  <img alt="Alt text" title="Title text" src="https://user-images.githubusercontent.com/default" width=70>
</picture>
```

```html
<!-- without sources -->
<picture>
  <img alt="Alt text" title="Title text" src="https://user-images.githubusercontent.com/default" width=70>
</picture>
```

```html
<!-- with unsupported sources -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/dark">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/light">
  <source media="(prefers-color-scheme: colorblind)" srcset="https://user-images.githubusercontent.com/light">
  <img alt="Alt text" title="Title text" src="https://user-images.githubusercontent.com/default" width=70>
</picture>
```

BTW, the `<preview>` tag is supported on all websites, we may need to rename our test name to ``Strip `<picture>` links``.

**Comment by mondeja** [comment]
Github supports `prefers-color-scheme: colorblind`? Where can I find information about it? The other cases that you've mentioned are working well, but yes, we need tests for them.

There are a lot of more cases where the strip is failing. Putting a `<picture>` inline code block before another valid `<picture>` HTML block. Or `<picture>` blocks inside codeblocks, which must not be rewritten. I've been searching for a tool to rewrite Markdown using a parser but all the tools that I've found are designed to convert to Markdown to HTML. Do you know one?

**Comment by LitoMore** [comment]
`colorblind` is just a random word. We should strip all other lines.

This might be what we want: https://github.com/remarkjs/remark/tree/main/packages/remark-parse

I just checked the source code of Prettier and then found the `remark-parse`.
